openapi: 3.0.0
info:
  title: Ecommerce API
  description: API for managing users and products
  version: 1.0.0
servers:
  - url: http://localhost:3001

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    product:
      type: object
      properties:
        name:
          type: string
          example: "sample"
        description:
          type: string
        price:
          type: number
          format: float
        category:
          type: string
        image:
          type: string
          format: binary

paths:
  /api/products/:
    get:
      summary: Get all products
      security:
        - JWT: []
      tags:
        - Products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/product"

    post:
      summary: Create a new product
      security:
        - JWT: []
      tags:
        - Products
      requestBody:
        description: The product to create
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/product"
      responses:
        "201":
          description: The product is created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
  /api/products/{productId}:            
    patch:
      summary: Update a product
      security:
        - JWT: []
      parameters: 
        - name: productId
          in: path
          description: Product to edit
          required: true
          schema:
            type: string
      tags:
        - Products
      requestBody:
        description: The product to update
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/product"
      responses:
        "200":
          description: The updated product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
        "404":
          description: Post not found

    delete:
      summary: Delete a product
      security:
        - JWT: []
      tags:
        - Products
      requestBody:
        description: The prdouct to delete
          schema:
            $ref: "#/components/schemas/[]"
      responses:
        "200":
          description: Post deleted successfully
        "404":
          description: Post not found

  /api/users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: The created user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /api/users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
    put:
      summary: Update a user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: The updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
    delete:
      summary: Delete a user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: User not found
